
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.sofia.soap;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2019-06-21T00:26:57.498+03:00
 * Generated source version: 2.7.7
 * 
 */

@javax.jws.WebService(
                      serviceName = "CalculatorServiceImpService",
                      portName = "CalculatorServiceImpPort",
                      targetNamespace = "http://soap.web.sofia.com/",
                      wsdlLocation = "http://localhost:8080/calculator/calculatorSOAP?wsdl",
                      endpointInterface = "CalculatorService")
                      
public class CalculatorServiceImpl implements CalculatorService {

    private static final Logger LOG = Logger.getLogger(CalculatorServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see CalculatorService#doOperation(MathOperation  arg0 )*
     */
    public java.lang.Double doOperation(com.sofia.soap.MathOperation arg0) {
        LOG.info("Executing operation doOperation");
        System.out.println(arg0);
        try {
            java.lang.Double _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see CalculatorService#getHistory(*
     */
    public java.util.List<com.sofia.soap.HistoryRecord> getHistory() {
        LOG.info("Executing operation getHistory");
        try {
            java.util.List<com.sofia.soap.HistoryRecord> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see CalculatorService#getHistoryByDate(java.lang.String  arg0 )*
     */
    public java.util.List<com.sofia.soap.HistoryRecord> getHistoryByDate(java.lang.String arg0) {
        LOG.info("Executing operation getHistoryByDate");
        System.out.println(arg0);
        try {
            java.util.List<com.sofia.soap.HistoryRecord> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
