package com.sofia.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2019-06-21T00:26:57.557+03:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "CalculatorServiceImpService", 
                  wsdlLocation = "http://localhost:8080/calculator/calculatorSOAP?wsdl",
                  targetNamespace = "http://soap.web.sofia.com/") 
public class CalculatorServiceImpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.web.sofia.com/", "CalculatorServiceImpService");
    public final static QName CalculatorServiceImpPort = new QName("http://soap.web.sofia.com/", "CalculatorServiceImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/calculator/calculatorSOAP?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalculatorServiceImpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/calculator/calculatorSOAP?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalculatorServiceImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalculatorServiceImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorServiceImpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CalculatorServiceImpService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CalculatorServiceImpService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CalculatorServiceImpService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CalculatorService
     */
    @WebEndpoint(name = "CalculatorServiceImpPort")
    public CalculatorService getCalculatorServiceImpPort() {
        return super.getPort(CalculatorServiceImpPort, CalculatorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorService
     */
    @WebEndpoint(name = "CalculatorServiceImpPort")
    public CalculatorService getCalculatorServiceImpPort(WebServiceFeature... features) {
        return super.getPort(CalculatorServiceImpPort, CalculatorService.class, features);
    }

}
